const PSEUDO_MESSAGES = [
  "I don't know how to spell a lot of things.",
  "He only had one drink but he's completely wasted.",
  'We stayed an extra night because we were having so much fun.',
  'The airplane went through such bad turbulence that everyone thought they were going to die.',
  'The computer is dying on me.',
  'The laptop became warm.',
  'He’s a chemistry whiz.',
  "If you don't tell me where he went, I am going to start crying.",
  'The view is breathtaking.',
  'I am about as tall as my father now.',
  'I trust you so much.',
  'I would like to make toast.',
  "I'm your lucky fellow then.",
  'He was in a bluegrass band with his father.',
  'He is my grandfather.',
  'They had to decide between buying diapers and buying ramen to feed themselves.',
  'How long did you think you could get away with this?',
  'Do you know what day it is?',
  'How dare you!',
  "I'm actually newly single.",
  'We will walk in the garden later.',
  'I’d like to talk about the benefits of having a pet pig.',
  "I'll talk you through every step of the aquatic soccer game.",
  'Judith Jarvis Thompson is the best philosopher of all time.',
  'According to the papers, there was a big fire in the town.',
  "I'm your lucky fellow then.",
  "My grandmother's death was a big shock.",
  "You don't need to leave so early.",
  'He is my classmate.',
  'People always have justifications for hurting others, but they are rarely good justifications.',
  'This is the biggest dog in the world.',
  "This is the biggest cat that I've ever seen.",
  'Chicago is one of the oldest cities in the Midwest.',
  'She always forgets her purse.',
  'The cat jumped over the fence.',
  "Mike's mother lived in a big city before she married.",
  'He stood no chance against her in a fight.',
  'Look at the blackboard!',
  'How long was she on the run before they caught her?',
  'She hated first dates.',
];

const PSEUDO_NAMES = ['Me', 'Monica', 'Jane', 'Davy', 'Audrey', 'Judy'];
const THUMB_STYLE = {
  backgroundColor: '#a0a0a5',
  borderRadius: '6px',
  boxShadow: '0 0 8px rgba(4, 0, 29, 0.25)',
  opacity: '0.75',
  right: '4px',
  width: '6px',
  zIndex: '200',
};
export { PSEUDO_MESSAGES,PSEUDO_NAMES, THUMB_STYLE };
