on:
  push:
    branches:
      - main
jobs:
  publish-wiki:
    runs-on: ubuntu-latest
    concurrency:
      group: publish-wiki
      cancel-in-progress: true
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Publish wiki
        uses: Andrew-Chen-Wang/github-wiki-action@v4
